### ISSUE TITLE
check docker hub build v2020 (:latest)

### ISSUE THREAD

**Issue by tbugfinder** [bioexcel/gromacs-docker#4]
Hello,

I've noticed that a new build is available on dockerhub.
After pulling the image gromacs doesn't startup properly.
Did the build finish successfully?
```
$ ls -l /gromacs
total 0
drwxr-xr-x 2 root root 26 Apr  7 10:17 bin


$ /gromacs/bin/gmx
/gromacs/bin/gmx: 12: /gromacs/bin/gmx: /gromacs/bin.SSE2/gmx: not found

```

Thanks & Best

**Comment by ffuen7es** [comment]
+1 on this one. Same impasse. I don't know how to resolve. If this is not a bug, please help.

C:\Users\ferna\Desktop\gromacs_1aki6>docker run --publish 8000:8080 --name ctest5 test5
/gromacs/bin/gmx: 12: /gromacs/bin/gmx: /gromacs/bin.SSE2/gmx: not found

**Comment by sreyoshi09** [comment]
+2 on this one. I am stuck at the place. Please fix this issue.

**Comment by mabraham** [comment]
The automated build on docker cloud failed to build all the things (https://hub.docker.com/repository/docker/gromacs/gromacs/builds/9e25e8b1-ccb8-4fea-bfb4-bce2f9f6f770), but I'm not sure why. I've reverted the last change, to see if that was somehow responsible. Otherwise I'll try a manual build of the container and see if something better results

**Comment by mabraham** [comment]
That also seems to not build the gmx binaries. Based on https://hub.docker.com/repository/docker/gromacs/gromacs/builds/4e26c7d9-2104-4886-87e4-347008d9d7f4 I'm guessing https://github.com/bioexcel/gromacs-docker/blob/dev/Dockerfile#L82 doesn't work as expected on Docker cloud, because it does work for me locally

**Comment by mabraham** [comment]
Hopefully https://hub.docker.com/repository/registry-1.docker.io/gromacs/gromacs/builds/5055e835-2b5d-4628-a505-305beb1522da will show some progress, and then I can make the full fix

**Comment by tbugfinder** [comment]
Could it be an issue with the default shell type?

**Comment by mabraham** [comment]
That's one of my theories, yes. Or that the interpolation from a variable set in a FROM statement doesn't work properly (or not properly any more)

**Comment by mabraham** [comment]
That shows progress. probably can fix tomorrow

**Comment by mabraham** [comment]
Hopefully a fixed gromacs:gromacs/dev version is building now

**Comment by mabraham** [comment]
The build is still timing out. I suspect that's from a combination of factors.

**Comment by mabraham** [comment]
I pulled the FFTW build into another container, used the ubuntu libraries for blas and lapack, and worked around a glitch with openmp+cmake. That will all speed the build up a lot.

**Comment by mabraham** [comment]
Not fast enough, however. In the long term, we'll need a way to factor out the build for each SIMD flavor into its own Dockerfile so that we can use the cloud build without running into the 240 minute timeout.

**Comment by tbugfinder** [comment]
Is the timeout applied to a single Dockerfile build, even if e.g. multiple build / from stages would be added?

**Comment by mabraham** [comment]
Yes, it's a time limit per Dockerfile. At some point we will want to offer many more flavours of gmx in the same container, so there's no choice but to factor out the individual builds to other Dockerfiles. I'm leaning towards adopting https://github.com/NVIDIA/hpc-container-maker (as main GROMACS has done for generating its CI containers) but first I want to work out if there's a way to have this repo contain all the Dockerfiles, and still build gromacs/gmx-cuda-10.2-mpi-avx256:* etc. as well as the usual top-level gromacs/gromacs:*

**Comment by mabraham** [comment]
I did use hpccm to make a bunch of preliminary images and combined them into gromacs/gromacs:dev image that built successfully. Can someone test that it works with CUDA? Then I'll make it gromacs/gromacs:latest.

**Comment by tbugfinder** [comment]
I just started gromacs:dev on a GPU instance successfully with singularity, cuda10.2. `nvidia-smi` shows low GPU use up to now. So I'm wondering which type of reference parameters we could share for testing.
```
Command line:
  gmx mdrun -ntomp 10 -ntmpi 4 -s test_5min.tpr -c confout.gro
```

**Comment by mabraham** [comment]
That might be because I accidentally built it in Debug mode. Give it an hour and pull and try again!

**Comment by tbugfinder** [comment]
That was a real boost 👍

**Comment by sha256feng** [comment]
> Hello,
> 
> I've noticed that a new build is available on dockerhub.
> After pulling the image gromacs doesn't startup properly.
> Did the build finish successfully?
> 
> ```
> $ ls -l /gromacs
> total 0
> drwxr-xr-x 2 root root 26 Apr  7 10:17 bin
> 
> 
> $ /gromacs/bin/gmx
> /gromacs/bin/gmx: 12: /gromacs/bin/gmx: /gromacs/bin.SSE2/gmx: not found
> ```
> 
> Thanks & Best

Did you solve this problem? I am running on an ubuntu machine with AMD CPU and came across the same problem.

**Comment by tbugfinder** [comment]
The image with dev tag works for me.

**Comment by sha256feng** [comment]
Thanks for sharing the information. The dev version works out for me too. Though the tag dev is a dangerous tag. Anytime it can be updated and be a different one.

**Comment by tbugfinder** [comment]
I think it's intermediate while resolving the issue.

**Comment by mabraham** [comment]
Yes I've been working more on the back end so it's easier to fix more things and support more build configurations without bloating the container size excessively. Hopefully I can make a new latest tag today or tomorrow.

**Comment by mabraham** [comment]
You can now `docker pull gromacs/gromacs:latest` to get the updated packages. I plan to update that to 2020.2 next week when that is released

**Comment by tbugfinder** [comment]
Hi @mabraham ,
thanks for updating.
As :dev and :latest were rebuilt, I've downloaded those new images. Actually GPU utilization is down to 1%. Therefore I'm wondering if you noticed the same or Debug is enabled?


Thanks
